[project]
authors = ["Hossein Ghorbanfekr <hgh.comphys@gmail.com>"]
channels = ["conda-forge"]
description = "Add a short description here"
name = "gpu-monitoring-tool"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = "3.12.*"
nvidia-ml-py = ">=12.570.86,<13"

[pypi-dependencies]
plotext = ">=5.3.2, <6"
