[build-system]
requires      = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where = ["src"]

[project]
name = "gtop"
version = "0.1.0"
description = "A lightweight CLI tool to monitor GPU."
readme = "README.md"
authors = [{ name = "Hossein Ghorbanfekr", email = "hgh.comphys@gmail.com" }]
license = "MIT"
license-files= ["LICENSE"]
keywords = ["GPU"]
dependencies = [
	'nvidia-ml-py>=11.450.129',
	'plotext>=5.2.8',
]
requires-python = ">=3.8"

[project.optional-dependencies]
dev = ["pytest", "mypy", "black", "isort"]

[project.urls]
Homepage = "https://github.com/hghcomphys/gpu-monitoring-tool" 

[project.scripts]
gtop = "gtop.cli:main"
